### ISSUE TITLE
octo-where ?

### ISSUE THREAD

**Issue by dirad** [jh3y/jh3y.github.io#1]
Hi, your code is inspiring.

Why is OCTO everywhere?   Is it your own note or left from something?

**Comment by jh3y** [comment]
Hi there @dirad!

Thanks for the kind words :smile: It's much appreciated.

Ha. I assume you are referring to `octo-nav` etc. I wanted to create a layout structure for a push in style menu. I thought I might use it elsewhere so I developed it in a separate repo. When you create a new repo on Github, it gives you repository name suggestions. I think it suggested like `octo-something-something` so I just called it `octo-nav` :laughing: 

Hope that clears it up!

@jh3y

**Comment by dirad** [comment]
=]   Thanks for the reply.

Is there a reason you chose to use tag attributes of the octo-properties and not classes or something else?  I do like it - just wondering.

**Comment by jh3y** [comment]
No problem @dirad .

Hmm. I think at the time, it was just a design choice. Using data attributes for components on a page similar to how you might prefix a classname with `js-` to signify a JavaScript component. This could easily be done with classes. There is no real difference in terms of performance.

For me personally, I like to try and be open minded and try different approaches with my code to learn new styles and techniques.

@jh3y
